import type { ValidationScenarioDefinition } from "../core/contracts";

export const SCENARIO_CATALOG: ValidationScenarioDefinition[] = [
  {
    id: "P01",
    name: "Head-to-head latest recall under pressure",
    family: "memory",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["quick", "quick_live", "production"],
    requiredMetricKeys: [
      "latest_fact_accuracy_rate",
      "required_fact_field_completeness_rate",
      "stale_fact_mismatch_rate",
      "passive_vs_history_win_rate",
    ],
    failureClassification: "retrieval_miss",
  },
  {
    id: "P02",
    name: "History-only baseline characterization",
    family: "memory",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["quick", "quick_live", "production"],
    requiredMetricKeys: ["required_fact_field_completeness_rate", "stale_fact_mismatch_rate"],
    failureClassification: "retrieval_miss",
  },
  {
    id: "P03",
    name: "Passive durability after history clear",
    family: "memory",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["production"],
    requiredMetricKeys: ["latest_fact_accuracy_rate", "passive_vs_history_win_rate"],
    failureClassification: "retrieval_miss",
  },
  {
    id: "P04",
    name: "Compaction hysteresis transition correctness",
    family: "mechanism",
    supportedModes: ["deterministic"],
    supportedProfiles: ["quick", "production"],
    requiredMetricKeys: ["hysteresis_transition_correctness_rate", "compaction_trigger_correctness_rate"],
    failureClassification: "contract_violation",
  },
  {
    id: "P05",
    name: "Age-backfill cadence correctness",
    family: "mechanism",
    supportedModes: ["deterministic"],
    supportedProfiles: ["quick", "production"],
    requiredMetricKeys: ["age_backfill_cadence_violation_count"],
    failureClassification: "contract_violation",
  },
  {
    id: "P06",
    name: "Compaction drain wait behavior",
    family: "mechanism",
    supportedModes: ["deterministic"],
    supportedProfiles: ["quick", "production"],
    requiredMetricKeys: ["compaction_drain_wait_applied_rate"],
    failureClassification: "contract_violation",
  },
  {
    id: "P07",
    name: "Compaction drain timeout fail-open",
    family: "robustness",
    supportedModes: ["deterministic"],
    supportedProfiles: ["production"],
    requiredMetricKeys: ["compaction_drain_timeout_recovery_rate", "step_timeout_rate"],
    failureClassification: "timeout_or_latency",
  },
  {
    id: "P08",
    name: "Deterministic fallback commit behavior",
    family: "mechanism",
    supportedModes: ["deterministic"],
    supportedProfiles: ["quick", "production"],
    requiredMetricKeys: ["fallback_commit_success_rate"],
    failureClassification: "contract_violation",
  },
  {
    id: "P09",
    name: "Hydration relevance precision",
    family: "memory",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["production"],
    requiredMetricKeys: ["hydration_precision_at_k"],
    failureClassification: "retrieval_miss",
  },
  {
    id: "P10",
    name: "Hydration false-retrieval suppression",
    family: "memory",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["production"],
    requiredMetricKeys: ["hydration_false_positive_rate"],
    failureClassification: "retrieval_miss",
  },
  {
    id: "P11",
    name: "Embedding retrieval activation",
    family: "mechanism",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["quick_live", "production"],
    requiredMetricKeys: ["embedding_query_activation_rate"],
    failureClassification: "contract_violation",
  },
  {
    id: "P12",
    name: "Embedding degraded fail-open",
    family: "robustness",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["production"],
    requiredMetricKeys: ["embedding_fail_open_success_rate"],
    failureClassification: "provider_failure",
  },
  {
    id: "P13",
    name: "Thread isolation",
    family: "core_contract",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["quick", "quick_live", "production"],
    requiredMetricKeys: ["thread_isolation_violation_count"],
    failureClassification: "isolation_leak",
  },
  {
    id: "P14",
    name: "One-call + streaming non-regression",
    family: "core_contract",
    supportedModes: ["deterministic", "live"],
    supportedProfiles: ["quick", "quick_live", "production"],
    requiredMetricKeys: ["one_call_invariant_rate", "stream_final_equivalence_rate"],
    failureClassification: "contract_violation",
  },
];

export function getScenarioById(id: string): ValidationScenarioDefinition | undefined {
  return SCENARIO_CATALOG.find((scenario) => scenario.id === id);
}
